### ISSUE TITLE
Any plans to release a NuGet package?

### ISSUE THREAD

**Issue by lalibi** [alveflo/MediatR.Plugins#1]
What the title says basically. ATM I have this repository as a submodule in my solution, but it would be nice to have a NuGet package. Or possibly one for each plugin.

Any plans for that?

**Comment by alveflo** [comment]
Sure, I'll fix a nuget package as soon as possible!

**Comment by alveflo** [comment]
Sure, I'll fix this as soon as possible. Not quite sure if I'll go for one package or one per plugin though.

If I go for one per plugin - what plugin are you using?

**Comment by lalibi** [comment]
`Caching` and `Serilog` for the time being.

**Comment by alveflo** [comment]
Hey @lalibi , this package is now available at nuget!

https://www.nuget.org/packages/MediatR.Plugins/
